### ISSUE TITLE
attributes.csv in Node-RED as HomeAssistant Addon

### ISSUE THREAD

**Issue by PITT72** [dirkjanfaber/node-red-contrib-victron-modbus#3]
Is it possible to run this node in Node-Red as HomeAssistant addon? I already tried everythink I could imagine.
The userDir for the addon is in my case /addon_configs/a0d7b954_nodered/
This is the directory mapped as /config in Node-Red. Even with the attributes.csv file present, the Dropdown does not show any data.
If I ssh into the Addon (docker container) I can see the attributes.csv in the userDir folder.

**Comment by PITT72** [comment]
I don't know why, but after I imported the example read-gx-serial.json, it suddently start working. The Dropdown is now filled. My old flow was still not showing the dropdown data. If I drag a new node from the sidebar and create a new flow, it works.

**Comment by dirkjanfaber** [comment]
Closing it as it apparently works now.
