### ISSUE TITLE
Uint32's register not reporting the correct value on reading

### ISSUE THREAD

**Issue by xithurbi** [dirkjanfaber/node-red-contrib-victron-modbus#5]
Working on a Node-RED project with differents products (BBB, Venus, Cerbo and and Ekrano) trying to retrieve some register's value, I notice if the value is Uint32, the node do not report me it as it should.

Example : Register 3005 : com.victronenergy.tank_Remaining_d_m3_3005_uint32_10000_R
send me back : 
: msg : Object
object
topic: "0df7a248e3493652"
messageId: "65d9c4e3ff4604ad95b6ebbf"
**payload: 0**
**type: "uint32"**
scalefactor: "10000"
enum: undefined
queueLengthByUnitId: object
unitId: 20
queueLength: 0
queueUnitId: 20
unitId: 20
modbusRequest: object
value: undefined
unitid: 20
fc: 3
**address: 3005**
**quantity: 1**
emptyMsgOnFail: undefined
keepMsgProperties: undefined
messageId: "65d9c4e3ff4604ad95b6ebbf"
responseBuffer: objec.....

![image](https://github.com/dirkjanfaber/node-red-contrib-victron-modbus/assets/124831302/a77cde0e-cc08-48e5-8b2b-15fe56be3eb3)

But I still have 23liters or (0.023m3) in the tank !
![image](https://github.com/dirkjanfaber/node-red-contrib-victron-modbus/assets/124831302/cacba457-e40e-4887-bd5b-a01c9b181930)

Using standing modbus reader :

Fuel : msg : Object
object
topic: "Fuel"
payload: array[2]
**0: 0
1: 232**
responseBuffer: object
data: array[2]
buffer: buffer[4]
input: object
topic: "Fuel"
from: "Carburant"
payload: object
unitid: "20"
fc: 3
**address: "3005"**
**quantity: "2"**
messageId: "65d9c536ff4604ad95b6ec2f"
queueLengthByUnitId: object
queueUnitId: 20....

![image](https://github.com/dirkjanfaber/node-red-contrib-victron-modbus/assets/124831302/b6c4a3d9-e56a-4dd8-9f0c-44950ff02aa6)

So It looks like the node has some register reading trouble.
I have the same troible with Date and Time register (830) reading and the Tank capacity (3001).

**Comment by dirkjanfaber** [comment]
Thanks for reporting. 

Created a new release, adding support for (u)int32 values. Only tested this limited, so if it does not work correctly, please create a new issue, referring to this one.
